### ISSUE TITLE
Wallet (Web)

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#17]
Consists of 
- [x] https://github.com/walt-id/waltid-wallet-backend/issues/1
- [x] https://github.com/walt-id/waltid-web-wallet/issues/3
- [x] User Management
- [x]  [DID registration (upon registration)](https://github.com/walt-id/waltid-wallet-backend/issues/6)
- [x] [Hosting](https://github.com/walt-id/waltid-wallet-backend/issues/3) 
- [x] Documentation _via docs.walt.id_

**Comment by philpotisk** [comment]
Hosting is done. Find the links for Issuer/Verifier and the Wallet at these endpoints:

https://issuer.waltid.org/login

https://verifier.waltid.org/

https://wallet.waltid.org/

@dombrn please review.
