### ISSUE TITLE
Data Exchange Protocol (OIDC)

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#18]
- [x] VC/VP Presentation
- [x] Documentation of VC/VP Presentation _via docs.walt.id_
- [x] VC Issuance (preliminary)
- [x] Documentation of VC Issuance (preliminary) _via docs.walt.id_
