### ISSUE TITLE
Support of RSA keys

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#26]
RSA keys should be fully supported.

- [x] Key generation
- [x] DID key creation
- [x] DID web creation
- [x] DID ebsi creation
- [x] Public Key import in PEM format
- [x] Public Key import in JWK format
- [x] Private Key import in PEM format
- [x] Private Key import in JWK format
- [x] Private RSA key export (PEM)
- [x] Public RSA key export (PEM) 
- [x] Private RSA key export (JWK)
- [x] Public RSA key export (JWK) 
- [x] Singing VCs
- [x] Creating VPs
- [x] Verifying VC/VPs
- [x] Resolving RSA-based did:keys

**Comment by waltkb** [comment]
Can be closed? @philpotisk
