### ISSUE TITLE
Onboarding Portal

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#33]
- [x] Web-wallet-backend: Add empty VP (signed by did:web) at the pushAuthorizationRequest
- [x] Onboarding-backend: Verify VP (resolve did:web, signature)
- [x] Onboarding-portal: Skip auth-page + show authenticated data (did:web)
- [x] Onboarding-portal: Verifies domain authentication code and issues VC
- [x] Web-wallet: Acceptance & storage of VC
