### ISSUE TITLE
NFT Kit (MVP)

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#36]
- [x] Minting NFTs on various networks
- [x] Fetching NFTs from different networks
- [x] Craft first version of developer docu

**Comment by philpotisk** [comment]
NFT Kit was implemented and open sourced here https://github.com/walt-id/waltid-nftkit
