### ISSUE TITLE
Delegation & Mandates

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#37]
- [ ] Implement data-model and JSON schema for a VerifiableMandate. Note that the VM contains a section for the OPA-config (based on Rego https://www.openpolicyagent.org/docs/latest/#rego)
- [ ] The Auditor should be extended to run the OPA Policy Engine https://github.com/open-policy-agent/opa and to execute Rego Policies
- [ ] A "MandatePolicy" in the Auditor shall be in-place for verifying VerifiableMandates
- [ ] Demo with the CLI tool how to issue and verify VMs
- [ ] Wallet extension for issuing VMs
