### ISSUE TITLE
Launch IDP Kit

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#43]
- [x] Dev deployment at: idp.walt-test.cloud
- [x] Stable deployment at: idp.walt.id
- [x] Update readme + license
- [x] Document IDP Kit at https://docs.walt.id/v/idp-kit
   - [x] Getting started, ... (as other sections)
   - [x] Keycloak integration
   - [x] Example configuration
   - [x] NFT Kit integration
      - [x] SIWE integration
- [x] Update Website
