### ISSUE TITLE
Add IOTA ecosystem

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#53]
### Describe the solution you'd like

- [ ]  Add did:iota registration & resolution
- [ ] VC issuance according to the IOTA specs
- [ ] VC verification incl. revocation check
