### ISSUE TITLE
Extend Velocity Ecosystem

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#55]
### Describe the solution you'd like

- [ ] https://github.com/walt-id/waltid-ssikit/issues/149
- [ ] https://github.com/walt-id/waltid-ssikit/issues/152
- [ ] https://github.com/walt-id/waltid-ssikit/issues/153
- [ ] https://github.com/walt-id/waltid-ssikit/issues/154
